### ISSUE TITLE
Custom Sript URL - doesn't work with pastebin.com

### ISSUE THREAD

**Issue by Hawky333** [Skateside/pocket-grimoire#124]
I have the same script uploaded to GitHub and Pastebin (in raw format):
1) https://raw.githubusercontent.com/Hawky333/BotCT-game/main/trouble_10
2) https://pastebin.com/raw/vGhspRxG
Link (1) for GitHub can be provided as URL for custom script and works fine but there is an issue and NetworkError when link (2) is provided.

**Comment by Hawky333** [comment]
Script works OK also when URL is linked to a RAW TXT file hosted on dpaste.com.
In this case URL should look like in this example https://dpaste.com/2YMHSP3RH.txt

**Comment by Skateside** [comment]
Hi @Hawky333 

I'm afraid that I'm not going to be able to fix this one. The issue that you've described is caused by a CORS error. This is something that Paste Bin would need to sort out (and they might not be willing to change much for such a small project as the Pocket Grimoire). I've never used Paste Bin before, but it might be possible to allow the Pocket Grimoire to read the JSON file?

As a work around, you can copy the contents of the JSON file and paste it into the larger text field ("Paste from clipboard")

Sorry I can't help more
Skateside

**Comment by Skateside** [comment]
Hi @Hawky333 

I've taken another look and I think I've found a way around the issue. Pastebin URLs should work now.

Cheers
Skateside

**Comment by Hawky333** [comment]
Great job! I have checked, Pastebin URLs work fine.
Thank you :)
