### ISSUE TITLE
Allow users to create custom info tokens

### ISSUE THREAD

**Issue by Skateside** [Skateside/pocket-grimoire#37]
This is based on pull request #35

**Comment by Skateside** [comment]
Looking at it, we probably have too many info tokens already. The official grimoire has these info tokens:

- **You** are
- **This player** is
- Did you **vote** today?
- Did you **nominate** today?
- These characters are **not in play**
- This character **selected** you (_we don't have this one in the Pocket Grimoire right now_)
- This is the **demon**
- These are you **minions**

If anything, we should remove these ones:

- These characters in **in play**
- This **ability** targeted you
- You have this **ability**
- Your **choice**?
- Use your **ability** now?

Is the ability to add custom info tokens actually useful?

**Comment by zenador** [comment]
Custom info tokens are useful for custom abilities, e.g. homebrew characters or Amnesiac. Also, storytellers may have their own preferences on the tokens they want to use, e.g. I want one that says "use your once per game ability now?" to reduce any chances of a mistake (sometimes players don't read the ability carefully or may forget). This allows everyone to have the tokens they want without needing to open an issue and argue their case and without creating too many tokens that not everyone might want to use.

I don't mind if you want to remove those you mentioned as long as we can have custom tokens, because if I ever want to use them I can just add them back in without affecting anyone else.

**Comment by Skateside** [comment]
OK, that makes some sense to me. Thinking about it, a custom info token is probably the best way to pass a word to the Mezepheles.

It's going to take a little work to get it right because I think we need the ability to edit and delete those info tokens, but I'll get to work added that. It's also an excuse to update the default tokens with the official ones because, as you say, users can always add back any that they miss.
