### ISSUE TITLE
Create a 'Show Demon Bluffs' button

### ISSUE THREAD

**Issue by binhnefits** [Skateside/pocket-grimoire#43]
It would be nice to have a 'Show Demon Bluffs' button that creates a pop up that has all 3 demon bluffs

**Comment by Skateside** [comment]
I've never done this because I don't think there's the space for it

![image](https://user-images.githubusercontent.com/817324/212635772-742b8cf1-c751-49f2-8b79-d692c7d7a1f8.png)

I think that only showing it one at a time is the same as a physical grimoire - you typically only show one bluff at a time.

**Comment by zenador** [comment]
In general it would be useful to have the ability to show multiple tokens at once from the 'show tokens' screen, e.g. for the Dreamer, Godfather, perhaps Amnesiac or homebrew/future characters. With a physical grimoire, you can take multiple physical tokens to show to a player at once (I've never shown the bluffs one at a time), but with the digital one, you have to show one token, wait for the player to acknowledge, go back to the screen and pick another and repeat as necessary. It's slightly more inefficient and time-consuming to show it one by one, but not sure if these use cases are worth the trouble of adding the ability to select and display multiple tokens, vs typing the character names out and showing it to the player (since there's probably not enough space to show multiple tokens in full anyway).

**Comment by binhnefits** [comment]
Maybe a popup that is swipeable or arrow buttons? With arrows and dot indicators or slide numbers to indicate it's swipeable.

![Capture2](https://user-images.githubusercontent.com/25918293/219786869-58ee989c-9118-4325-93a6-8680fc7bdc4c.PNG)

**Comment by Skateside** [comment]
OK, I can see how this might be useful. It'll take a little time to implement, but I'll see what I can do

**Comment by chepash** [comment]
Sorry, but I really want to add something to this topic.
From my experience as a game master, I've noticed a couple of things.

When I reveal the demon's bluff tokens one by one, the demon tends to forget the first one by the time they see the third. That's why I switch my phone to a horizontal position and always show them that way, also allowing the demon to take a photo of my phone screen:

![Screenshot_2023-05-29-16-48-43-336_com android chrome](https://github.com/Skateside/pocket-grimoire/assets/100382249/d2088dd7-84e3-4f81-b68b-0702ac48b94e)

Another issue is my personal dislike for the Lunatic character. On paper, they might seem incredibly fun, but as a game master, this character can become quite a headache. They can prolong the night significantly, and players usually notice this, quickly exposing the Lunatic. It's frustrating, even if you had an interesting game plan as a game master. In the original paper version of the game, the storytelling process for the Lunatic can be tedious. They sometimes want/need to see different bluff tokens. Moreover, I often see that people include the Lunatic into lot of custom scenarios.

To speed up the process with the Lunatic as much as possible, I have to open the application in another browser tab and duplicate the Demon's Bluffs there specifically for the Lunatic in the same location. It's a functional workaround, but still. I might accidentally close the second tab or mistakenly mix up the actual Demon's Bluffs with the Bluffs intended for the Lunatic. It would be great if this could be implemented within a single application.

Alright. I mostly complained without offering any solutions. I agree that perhaps there should be a button to reveal all 3 bluff tokens at once. And maybe a separate section/option to display other bluff tokens specifically for the Lunatic, if they are in the game. However, I understand that it may not be desirable to develop such functionality specifically for the Lunatic role. The solution should be something more universal. For example, a swipe to the right where you can assign three more bluff roles.

![image](https://github.com/Skateside/pocket-grimoire/assets/100382249/5a02476d-19e4-45ac-83cb-a1486e447270)

OR

![image](https://github.com/Skateside/pocket-grimoire/assets/100382249/b96f8da0-b8dd-4225-90a7-31f4649ec40d)

**Comment by Skateside** [comment]
Yeah, that makes sense. Legion can also end up with multiple sets of bluffs.

OK, since I've got a little time, I'll get started on this. It could be a bit of work to implement that and the multiple bluff sets, but it wouldn't be any fun if it were easy.

**Comment by Skateside** [comment]
@chepash I've moved your comment to a new ticket, #65 - this allows me to deploy the functionality to add multiple tokens to a dialog without being stuck behind your idea.

**Comment by binhnefits** [comment]
Thank you for the update! @Skateside
