### ISSUE TITLE
Allow Homebrew scripts to include known characters

### ISSUE THREAD

**Issue by Skateside** [Skateside/pocket-grimoire#48]
It should be possible to combine homebrew characters with known ones in an uploaded script. For example, a script of Trouble Brewing + an unreleased character should be possible without having to define everything about the already known characters.

**Comment by Skateside** [comment]
Hey @zenador 

Thanks for the PR! I've kept most of it, but I've had to remove a couple of bits:

- I already have generic icons for the teams, so I've used them. They're in keeping with the current icon style (although I might live to regret that if I think I can get away with #56)
- I've removed the night order from the character sheet. The order isn't on the paper given to players with a physical grimoire so I don't think it fits to include it here.

Cheers
Skateside

**Comment by zenador** [comment]
Thanks! Surprisingly there isn't really an official position on the night order being public info, the closest I could find is Evin from TPI saying "They can see the night sheet if they really want to" [here](https://www.reddit.com/r/BloodOnTheClocktower/comments/fr0lod/do_players_know_the_order_of_night_actions/), so it seems it isn't really private, maybe they just didn't want to print so much to distribute to players. When we play with custom scripts from the script tool we send everyone the night order sheet as part of the PDF. This seems like mechanical info the ST should answer any questions on, and having it public just saves everyone the trouble of asking ST when they want to figure out what interactions are possible or to plan their next night. Keeping it private would just give more experienced players (especially those who have been STs) an unfair advantage. One problem is that players might use it to try and figure out what roles are in play (like Monk/Poisoner in the reddit thread), but this is something that experienced players could do anyway, so the ST should be walking around randomly to mitigate that. That being said, since the official rules aren't clear on this, if your groups treat it as private info then I understand why you'd prefer to leave it out :)
